```
###############################
##                           ##
##  Deep Learning in Python  ##
##                           ##
###############################

§2 Introduction to TensorFlow in Python

§2.2 Linear models
```

# Loss functions

## What is the loss functions?

* **Fundamental TensorFlow operation**:

    * used to train a model
    
    * measure of model fit

* **Higher value $\rightarrow$ worse fit**:

    * minimize the loss function

## What are the common loss functions in TensorFlow?

* **TensorFlow has operations for common loss functions**:

    * mean squared error (MSE)
    
    * mean absolute error (MAE)
    
    * huber error

* **Loss functions are accessible from `tf.keras.losses()`**:

    * `tf.keras.losses.mse()`
    
    * `tf.keras.losses.mae()`
    
    * `tf.keras.losses.Huber()`

## Why is it in need to care about loss functions?

* **MSE**:
    
    * strongly penalizes outliers
    
    * high (gradient) sensitivity near minimum

* **MAE**:
    
    * scales linearly with the size of the error
    
    * low sensitivity near minimum

* **Huber**:
    
    * similar to MSE near minimum
    
    * similar to MAE away from the minimum

![Why do we care about loss functions](ref4.%20Why%20do%20we%20care%20about%20loss%20functions.jpg)

## Code of defining the loss function:

In [1]:
import pandas as pd
import numpy as np

housing = pd.read_csv('ref1. King county house sales.csv')

price_log = np.log(np.array(housing['price'], np.float32))
size_log = np.log(np.array(housing['sqft_lot'], np.float32))
targets = price_log
features = size_log
intercept = 0.1
slope = 0.1

predictions = intercept + features * slope

In [2]:
# Import TensorFlow under standard alias
import tensorflow as tf

# Compute the MSE loss
loss = tf.keras.losses.mse(targets, predictions)

loss

<tf.Tensor: shape=(), dtype=float32, numpy=145.44653>

In [3]:
# Define a linear regression model
def linear_regression(intercept, slope=slope, features=features):
    return intercept + features * slope

In [4]:
# Define a loss function to compute the MSE
def loss_function(intercept, slope, targets=targets, features=features):
    # Compute the predictions for a linear model
    predictions = linear_regression(intercept, slope, features)

    # Return the loss
    return tf.keras.losses.mse(targets, predictions)

In [5]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_targets, test_targets = train_test_split(
    features, targets, test_size=0.3, random_state=42)

In [6]:
# Compute the loss for test data inputs
loss_function(intercept, slope, test_targets, test_features)

<tf.Tensor: shape=(), dtype=float32, numpy=145.57338>

In [7]:
# Compute the loss for default data inputs
loss_function(intercept, slope)

<tf.Tensor: shape=(), dtype=float32, numpy=145.44653>

## Practice exercises for loss functions:

$\blacktriangleright$ **Package pre-loading:**

In [8]:
import pandas as pd
import numpy as np

$\blacktriangleright$ **Data pre-loading:**

In [9]:
housing = pd.read_csv('ref1. King county house sales.csv')
price = np.array(housing['price'], np.float32)

predictions = np.loadtxt('ref5. Predictions.csv', delimiter=',')

$\blacktriangleright$ **TensorFlow loss functions practice:**

In [10]:
# Import the keras module from tensorflow
from tensorflow import keras

# Compute the mean squared error (mse)
loss = keras.losses.mse(price, predictions)

# Print the mean squared error (mse)
print(loss.numpy())

141171604777.141


In [11]:
# Import the keras module from tensorflow
from tensorflow import keras

# Compute the mean absolute error (mae)
loss = keras.losses.mae(price, predictions)

# Print the mean absolute error (mae)
print(loss.numpy())

268827.9930163703


$\blacktriangleright$ **Package re-pre-loading:**

In [12]:
from tensorflow import constant, Variable, float32

$\blacktriangleright$ **Data re-pre-loading:**

In [13]:
features = constant([1., 2., 3., 4., 5.], dtype=float32)
targets = constant([2., 4., 6., 8., 10.], dtype=float32)

$\blacktriangleright$ **Loss function modification practice:**

In [14]:
# Initialize a variable named scalar
scalar = Variable(1.0, float32)


# Define the model
def model(scalar, features=features):
    return scalar * features


# Define a loss function
def loss_function(scalar, features=features, targets=targets):
    # Compute the predicted values
    predictions = model(scalar, features)

    # Return the mean absolute error loss
    return keras.losses.mae(targets, predictions)


# Evaluate the loss function and print the loss
print(loss_function(scalar).numpy())

3.0
